# Generated by Django 4.2.18 on 2025-01-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='created_by',
            new_name='artist',
        ),
    ]
